runtime: custom # or another supported version
env: flex

instance_class: F2

env_variables:
  DEEPAI_API_KEY: "be7ff4a9-4e9a-440f-83c7-c3c7444be508"
  MONGODB_URI: "mongodb+srv://denteyon:artwork@cluster0.lkrvm.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"


handlers:
- url: /stylesheets
  static_dir: public/stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto