runtime: nodejs14 # or another supported version

instance_class: F2

env_variables:
  DEEPAI_API_KEY: <API_KEY>
  MONGODB_URI: <API_KEY>


handlers:
- url: /stylesheets
  static_dir: public/stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
